### ISSUE TITLE
Illegal instructionの発生について

### ISSUE THREAD

**Issue by dinosauria123** [Kazuhito00/7segment-display-reader#1]
Raspberry pi ZEROで7segment-display-readerを動かそうと試みております。
Zeroなので、素のtensorflowは使えず、tfliteかtflite-microしか使えません。

tfliteでは、invokeの際にIllegal instructionが発生します。
また、tflite-microでは、hybrid modelは使えませんと怒られます。

一緒に配布されている7seg_classifier.tfliteをそのまま使っているのですが、
モデルの再構築が必要なのでしょうか。

こちらの用途では、１分に１回程度認識ができればよいです。

あと、LinuxPCでは問題なく動くことを確認しています。

なにかヒントがありましたら教えていただければ幸いです。

**Comment by dinosauria123** [comment]
すみません、動きました！

こちらにあるtflite_runtimeを使ったら動きました。
https://github.com/tensorflow/tensorflow/issues/38642#issuecomment-988572129

少しいじったファイルを置いておきます。
[sevensegreader.py.txt](https://github.com/Kazuhito00/7segment-display-reader/files/11767347/sevensegreader.py.txt)

最新の2.14ではIllegal instructionが発生するようです。
起動に20秒程かかりますが、認識は10秒くらいでできるようです。

これで７セグの自動読み取りカメラを作ろうと思っています。大変便利なプログラムを公開くださりありがとうございます！

**Comment by Kazuhito00** [comment]
解決できて良かったです。
また、解決に至る情報の記載ありがとうございます。
